### ISSUE TITLE
Dont want to load 

### ISSUE THREAD

**Issue by honzad** [creadri/LazyRoad#17]
when i start my server craftbukkit 1.2.5 this show in log:
    2012-04-09 16:36:36 [INFO] [LazyRoad] Enabling LazyRoad v0.7.5
    2012-04-09 16:36:36 [SEVERE] Error occurred while enabling LazyRoad v0.7.5 (Is it up to date?)
    java.lang.NoClassDefFoundError: com/creadri/util/FileManager
    at com.creadri.lazyroad.LazyRoad.onEnable(LazyRoad.java:62)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:250)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:232)
    at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:371)
    at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:358)
    at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:187)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:422)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
    Caused by: java.lang.ClassNotFoundException: com.creadri.util.FileManager
    at java.net.URLClassLoader$1.run(Unknown Source)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(Unknown Source)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:41)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    at java.lang.ClassLoader.loadClass(Unknown Source)
    ... 11 more

**Comment by wolfwoodbrbu** [comment]
https://github.com/creadri/LazyRoad/issues/18 to keep it the bug in 1 issue request.
