### ISSUE TITLE
Error on CB 1.2.5 R1

### ISSUE THREAD

**Issue by technogeek48** [creadri/LazyRoad#18]
I get this error on load:

18:36:05 [SEVERE] Error occurred while enabling LazyRoad v0.7.5 (Is it up to date?)
java.lang.NoClassDefFoundError: com/creadri/util/FileManager
    at com.creadri.lazyroad.LazyRoad.onEnable(LazyRoad.java:62)
    at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
    at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336)
    at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
    at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:250)
    at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:232)
    at org.bukkit.craftbukkit.CraftServer.reload(CraftServer.java:543)
    at org.bukkit.Bukkit.reload(Bukkit.java:182)
    at org.bukkit.command.defaults.ReloadCommand.execute(ReloadCommand.java:22)
    at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:166)
    at org.bukkit.craftbukkit.CraftServer.dispatchCommand(CraftServer.java:473)
    at org.bukkit.craftbukkit.CraftServer.dispatchServerCommand(CraftServer.java:469)
    at net.minecraft.server.MinecraftServer.b(MinecraftServer.java:596)
    at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:565)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:449)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.ClassNotFoundException: com.creadri.util.FileManager
    at java.net.URLClassLoader$1.run(URLClassLoader.java:217)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:205)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:41)
    at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:321)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:266)
    ... 16 more

I'm using CB 1.2.5 R1 (Recomended Build) on Ubuntu 11.10 with JRE7

any help is appreciated!

ciao

**Comment by Phr33d0m** [comment]
I can confirm having this exact error with the same CB version.

04:34:24 [INFO] [LazyRoad] Enabling LazyRoad v0.7.5
04:34:24 [SEVERE] Error occurred while enabling LazyRoad v0.7.5 (Is it up to date?)
java.lang.NoClassDefFoundError: com/creadri/util/FileManager
        at com.creadri.lazyroad.LazyRoad.onEnable(LazyRoad.java:62)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:215)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:381)
        at org.bukkit.craftbukkit.CraftServer.loadPlugin(CraftServer.java:250)
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:232)
        at net.minecraft.server.MinecraftServer.t(MinecraftServer.java:371)
        at net.minecraft.server.MinecraftServer.a(MinecraftServer.java:358)
        at net.minecraft.server.MinecraftServer.init(MinecraftServer.java:187)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:422)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)
Caused by: java.lang.ClassNotFoundException: com.creadri.util.FileManager
        at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:41)
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:29)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
        ... 11 more

**Comment by honzad** [comment]
i have same error :(

**Comment by mdemon** [comment]
same here

**Comment by wolfwoodbrbu** [comment]
I'm unable to replicate this error.

I've even downloaded the jar I have up on the site and used it with a server restart and a /reload and no error.

If you guys restart the server with the ver. 0.7.5 does it still throw the error?

**Comment by honzad** [comment]
i still have it it dont want to load :(
same error

**Comment by technogeek48** [comment]
same thing even with server restart, it's a shame this plugin looks soooooo cool.

**Comment by wolfwoodbrbu** [comment]
I just figured out what i was doing wrong to test for the error Time to delete the lazyroad folder and see what happens.

**Comment by wolfwoodbrbu** [comment]
yup there it is, I got the error guys i'll start debuggin now.

**Comment by honzad** [comment]
:))

**Comment by wolfwoodbrbu** [comment]
I have to edit the file that builds the plugin to include the MineUtil dependency I've just switched to Maven for this plugin and it may take a few hours for me to figure it out how to to it properly I'll have a 0.7.6 out by tonight I promise.

**Comment by technogeek48** [comment]
thank :)

**Comment by wolfwoodbrbu** [comment]
Got it fixed. Get it here.
http://dev.bukkit.org/server-mods/lazyroad/files/11-lazy-road-v0-7-6/

**Comment by technogeek48** [comment]
YAY!!!! It works!!!!! Thanx so much!!!
