### ISSUE TITLE
Unable to turn when there is not an empty space to left or right.

### ISSUE THREAD

**Issue by alexzielenski** [creadri/LazyRoad#2]
What the title says. I mean that a Java exception is raised when trying to turn with this config:

x = block
u = person

x–x–x–x–x–x
x–––––––––x  
x–––––u–––x
x–x–––u–––x
x–x–x–x–x–x

or

x–x–x–x–x–x
x–––––––––x  
x–––––u–––x
x–x–x–u–––x
x–x–x–x–x–x

As opposed to:

x–x–x–x–x–x
x–––––––––x  
x–––––u–––x
x–––––u–––x
x–x–x–x–x–x

I get these errors:

11:40:11 [SEVERE] Could not pass event PLAYER_MOVE to LazyRoad
java.lang.ArrayIndexOutOfBoundsException: 8
    at com.creadri.lazyroad.RoadEnabled.drawCorner(RoadEnabled.java:599)
    at com.creadri.lazyroad.RoadEnabled.drawRoad(RoadEnabled.java:146)
    at com.creadri.lazyroad.LazyRoadPlayerListener.onPlayerMove(LazyRoadPlayerListener.java:49)
    at org.bukkit.plugin.java.JavaPluginLoader$7.execute(JavaPluginLoader.java:286)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:180)
    at net.minecraft.server.Packet10Flying.a(SourceFile:126)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:464)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)
11:40:11 [SEVERE] Could not pass event PLAYER_MOVE to LazyRoad
java.lang.ArrayIndexOutOfBoundsException: 8
    at com.creadri.lazyroad.RoadEnabled.drawCorner(RoadEnabled.java:599)
    at com.creadri.lazyroad.RoadEnabled.drawRoad(RoadEnabled.java:146)
    at com.creadri.lazyroad.LazyRoadPlayerListener.onPlayerMove(LazyRoadPlayerListener.java:49)
    at org.bukkit.plugin.java.JavaPluginLoader$7.execute(JavaPluginLoader.java:286)
    at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:58)
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:338)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:180)
    at net.minecraft.server.Packet10Flying.a(SourceFile:126)
    at net.minecraft.server.NetworkManager.b(NetworkManager.java:226)
    at net.minecraft.server.NetServerHandler.a(NetServerHandler.java:92)
    at net.minecraft.server.NetworkListenThread.a(SourceFile:108)
    at net.minecraft.server.MinecraftServer.h(MinecraftServer.java:464)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:374)
    at net.minecraft.server.ThreadServerApplication.run(SourceFile:417)

**Comment by creadri** [comment]
I'll try to recreate this bug and correct it, thanks for reporting
